### ISSUE TITLE
Doesn't work well with Vivaldi browser based on Chromium project

### ISSUE THREAD

**Issue by Anongh** [anthonynosek/sprint-reader-chrome#22]
Thank you for making a better add-on than other competitors.

It works only once after installation.
Deactivating and reactivating an add-on also only works once.

I am using Vivaldi developer version 1.8.755.3 on Windows 8.1.

**Comment by anthonynosek** [comment]
Have you done any further investigation?
The extension has been designed to work in Chrome only.
