### ISSUE TITLE
remove google+

### ISSUE THREAD

**Issue by iveskins** [anthonynosek/sprint-reader-chrome#30]
as google+ is shutdown the button should be removed.

**Comment by Ankitkj1999** [comment]
I have fixed this issue.

**Comment by iveskins** [comment]
Oh, but your pull request doesn't seem to have any changes..

**Comment by Ankitkj1999** [comment]
Sorry for that i have just sent a new pull request

**Comment by iveskins** [comment]
closed in PR #36
