### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by skywinder** [anthonynosek/sprint-reader-chrome#34]
Hello. thank you for awesome tool and open sourcing it. I would be very glad about the dark mode theme for that

**Comment by 4t0m** [comment]
On the settings tab there is a drop-down menu that you can use to select a different color scheme.

**Comment by israelgonzalezb** [comment]
Here's a screenshot of the option and where to find it in the window.

<img width="894" alt="Screen Shot 2020-01-11 at 4 43 07 PM" src="https://user-images.githubusercontent.com/48233351/72212462-85540600-3491-11ea-9ad0-1eedb268efe2.png">

**Comment by skywinder** [comment]
thank you!
