### ISSUE TITLE
Google threatening to remove from store for not following "best practices"?

### ISSUE THREAD

**Issue by JamesNewton** [anthonynosek/sprint-reader-chrome#42]
In the store, I'm seeing a message that this extension may be removed because of some best practice issue.

Anyone know what the issue is? 

Is there a way I can help to make sure it remains available? I honestly depend on it.

**Comment by JamesNewton** [comment]
"This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions."
https://chromewebstore.google.com/detail/sprint-reader-speed-readi/kejhpkmainjkpiablnfdppneidnkhdif

**Comment by anthonynosek** [comment]
Thanks for posting this issue. 

Sprint Reader is largely undeveloped at this point in time due to other commitments however I would like to know that it can still be downloaded and installed from the Google Store. I can see that many people are still actively using the extension.

When I can, I will investigate and in the meantime- should anyone wish to add to this or provide information on what we need to do in order to resolve the issue regarding best practice- please add to this issue.

**Comment by JamesNewton** [comment]
I'm very happy that you are willing to keep it going. If I'm able, I will attempt to contribute. 

Strangely, I just checked again and the message is gone! 

The only thing I do see is "The developer has not provided any information about the collection or usage of your data."

**Comment by anthonynosek** [comment]
After a little investigation the solution is to migrate the extension to support the latest manifest version (version 3). The changes are not trivial to upgrade and support the new manifest so I will have to add this to a to-do list.

If anyone would like to tackle the migration to manifest version 3 it may expedite the resolution.

**Comment by JamesNewton** [comment]
It looks like the most difficult part is this?
https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers#changes_youll_need_to_make
(just to be very clear, I do NOT think I can help with this, except in very small / mindless ways. This type of code is not where I have experience.

**Comment by anthonynosek** [comment]
@JamesNewton Just an FYI, I have not forgotten you. I have spent time rewriting Sprint Reader to support Chrome Extensions Manifest v3 and I am 95% complete. I am working on it in the background with other tasks such as life, small kids etc :-)

Rest assured, my goal is to release soon (possibly to closed testing which will include yourself) and also to support Firefox.

All in good time- I am getting there.... slowly.

**Comment by anthonynosek** [comment]
@JamesNewton Have submitted version 3.0 to Google for review.
Of course, I have tested the extension, could you do a review for me once I publish it also?

**Comment by JamesNewton** [comment]
I thought I saw it update, but it's still on 2.5 in my browser. Anything I need to do to update it? Just wait for the release?

**Comment by anthonynosek** [comment]
You may have auto-updates disabled in Chrome. Just venture to “Manage Extensions” and force the update manually. I have tested the release path and the production extension updates with no issue.

Let me know if you continue to have problems.

**Comment by JamesNewton** [comment]
I don't see a way to force the update... I do see an "Update" button on the Manage Extensions section and when I press it, nothing happens. My installed version is 2.5 and the version I see in the chrome web store is 3.0. 

I can uninstall it and reinstall it, but I wonder if there is a way to debug the fact that it's not updating on this PC? It's Ubuntu, and Chrome is up to date.

**Comment by anthonynosek** [comment]
@JamesNewton I am not able to test Chrome on Ubuntu, my comments were for Chrome on Mac however I was assuming the update process is the same across Windows, Mac and Linux.

I shall investigate this when I have the time- will try and fire up a Linux VM to test. For the meantime, I suggest you uninstall and install the latest version directly from the store.

**Comment by JamesNewton** [comment]
Well... poop! I uninstalled 2.5 and when I try to install 3.0 from the store, I get an "Invalid manifest" error. The console.log just says
"Unchecked runtime.lastError: Invalid manifest"

**Comment by anthonynosek** [comment]
@JamesNewton I will close this issue as it is resolved.
Have opened a new one for your Linux Chrome issue which I will investigate.
