### ISSUE TITLE
"Invalid Manifest" error in Linux Chrome

### ISSUE THREAD

**Issue by anthonynosek** [anthonynosek/sprint-reader-chrome#44]
Well... poop! I uninstalled 2.5 and when I try to install 3.0 from the store, I get an "Invalid manifest" error. The console.log just says
"Unchecked runtime.lastError: Invalid manifest"

So now I can't use the extension at all! Sad face. 

I don't see any other debug info... Looking at the manifest, the only thing I notice is that there is no linux option for the hotkey, but I doubt that would cause the install to fail:
https://github.com/anthonynosek/sprint-reader-chrome/blob/master/manifest.json#L36

Having said that, it looks like other HAVE seen failures for this reason. The trick seems to be that it needs a default option?
https://groups.google.com/a/chromium.org/g/chromium-extensions/c/QqN2H2mVMuQ?pli=1

_Originally posted by @JamesNewton in https://github.com/anthonynosek/sprint-reader-chrome/issues/42#issuecomment-2380896906_

**Comment by anthonynosek** [comment]
@JamesNewton Can you let me know your setup, Linux distribution, source for Chrome etc?

**Comment by JamesNewton** [comment]
I've tried it on multiple machines. Ubuntu 18 and 22. Also Mint Cinnamon. Chrome is always up to date, latest. Version 128.0.6613.137 (Official Build) (64-bit)

pretty sure it just needs a default option in the manifest.

**Comment by anthonynosek** [comment]
@JamesNewton I will aim to release a new version with additions to the 'manifest' before the end of the week. We can see if that resolves the issue.

**Comment by anthonynosek** [comment]
@JamesNewton New version 3.0.1 has been submitted to the Chrome Store. Please update here once you have access to it.

**Comment by anthonynosek** [comment]
Version 3.0.2 released. Manifest has been updated.

**Comment by JamesNewton** [comment]
Works perfectly! Thank you!

**Comment by anthonynosek** [comment]
@JamesNewton will close this issue.
